services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "db"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
